# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled/Aniadir.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        Dialog.setBaseSize(QtCore.QSize(400, 300))
        self.btnSalir = QtWidgets.QDialogButtonBox(Dialog)
        self.btnSalir.setGeometry(QtCore.QRect(310, 260, 81, 32))
        self.btnSalir.setOrientation(QtCore.Qt.Horizontal)
        self.btnSalir.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.btnSalir.setObjectName("btnSalir")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 51, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 51, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 51, 17))
        self.label_3.setObjectName("label_3")
        self.teCodigo = QtWidgets.QLineEdit(Dialog)
        self.teCodigo.setGeometry(QtCore.QRect(80, 50, 113, 25))
        self.teCodigo.setObjectName("teCodigo")
        self.teNombre = QtWidgets.QLineEdit(Dialog)
        self.teNombre.setGeometry(QtCore.QRect(80, 100, 113, 25))
        self.teNombre.setObjectName("teNombre")
        self.teHoras = QtWidgets.QLineEdit(Dialog)
        self.teHoras.setGeometry(QtCore.QRect(80, 150, 113, 25))
        self.teHoras.setObjectName("teHoras")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 71, 17))
        self.label_4.setObjectName("label_4")
        self.btnAniadir = QtWidgets.QPushButton(Dialog)
        self.btnAniadir.setGeometry(QtCore.QRect(100, 190, 80, 25))
        self.btnAniadir.setObjectName("btnAniadir")

        self.retranslateUi(Dialog)
        self.btnSalir.accepted.connect(Dialog.accept) # type: ignore
        self.btnSalir.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Codigo"))
        self.label_2.setText(_translate("Dialog", "Nombre"))
        self.label_3.setText(_translate("Dialog", "Horas"))
        self.label_4.setText(_translate("Dialog", "Juego Nuevo"))
        self.btnAniadir.setText(_translate("Dialog", "Añadir Juego"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
