# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled/listar2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        Dialog.setBaseSize(QtCore.QSize(400, 300))
        self.btnsalir = QtWidgets.QDialogButtonBox(Dialog)
        self.btnsalir.setGeometry(QtCore.QRect(300, 10, 81, 32))
        self.btnsalir.setOrientation(QtCore.Qt.Horizontal)
        self.btnsalir.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.btnsalir.setObjectName("btnsalir")
        self.tablaLista = QtWidgets.QTableWidget(Dialog)
        self.tablaLista.setGeometry(QtCore.QRect(10, 50, 371, 231))
        self.tablaLista.setObjectName("tablaLista")
        self.tablaLista.setColumnCount(3)
        self.tablaLista.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tablaLista.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tablaLista.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255, 0))
        self.tablaLista.setHorizontalHeaderItem(2, item)

        self.retranslateUi(Dialog)
        self.btnsalir.accepted.connect(Dialog.accept) # type: ignore
        self.btnsalir.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tablaLista.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nombre"))
        item = self.tablaLista.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Genero"))
        item = self.tablaLista.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Num de horas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
