# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QDelete.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Videojuegos import Videojuegos
videojuegos = Videojuegos()
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 200)
        Dialog.setMinimumSize(QtCore.QSize(300, 200))
        Dialog.setMaximumSize(QtCore.QSize(300, 200))
        Dialog.setBaseSize(QtCore.QSize(300, 200))
        self.btnSalir = QtWidgets.QDialogButtonBox(Dialog)
        self.btnSalir.setGeometry(QtCore.QRect(220, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSalir.setFont(font)
        self.btnSalir.setOrientation(QtCore.Qt.Vertical)
        self.btnSalir.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.btnSalir.setObjectName("btnSalir")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 30, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.leCodigo = QtWidgets.QLineEdit(Dialog)
        self.leCodigo.setGeometry(QtCore.QRect(80, 60, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leCodigo.setFont(font)
        self.leCodigo.setObjectName("leCodigo")
        self.btnEliminar = QtWidgets.QPushButton(Dialog)
        self.btnEliminar.setGeometry(QtCore.QRect(90, 100, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setObjectName("btnEliminar")

        self.retranslateUi(Dialog)
        self.btnSalir.accepted.connect(Dialog.accept) # type: ignore
        self.btnSalir.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.btnEliminar.clicked.connect(self.eliminarVideojuego)
        self.btnSalir.clicked.connect(videojuegos.exportarVideojuegos)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Introduce el codigo del videojuego "))
        self.label_2.setText(_translate("Dialog", "que desee eliminar"))
        self.btnEliminar.setText(_translate("Dialog", "Eliminar"))

    def eliminarVideojuego(self):
        dialog = QtWidgets.QDialog()
        codigo = self.leCodigo.text()
        if codigo != "":
            if not(videojuegos.comprobarCodigo(codigo)):
                videojuegos.eliminarVideojuego(codigo)
                QtWidgets.QMessageBox.question(dialog, '', 'Videojuego Eliminado',
                    QtWidgets.QMessageBox.Yes)
            else:
                QtWidgets.QMessageBox.question(dialog, 'Error', 'No existe ningun videojuego con es codigo',
                    QtWidgets.QMessageBox.Yes)
        else:
            QtWidgets.QMessageBox.question(dialog, 'Error', 'No puede haber campos vacios',
                    QtWidgets.QMessageBox.Yes)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
