# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled/listar2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Videojuegos import Videojuegos
videojuegos = Videojuegos()

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        Dialog.setBaseSize(QtCore.QSize(400, 300))
        self.btnsalir = QtWidgets.QDialogButtonBox(Dialog)
        self.btnsalir.setGeometry(QtCore.QRect(300, 10, 81, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnsalir.setFont(font)
        self.btnsalir.setOrientation(QtCore.Qt.Horizontal)
        self.btnsalir.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.btnsalir.setObjectName("btnsalir")
        self.tablaLista = QtWidgets.QTableWidget(Dialog)
        self.tablaLista.setGeometry(QtCore.QRect(10, 50, 371, 231))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tablaLista.setFont(font)
        self.tablaLista.setObjectName("tablaLista")
        self.tablaLista.setColumnCount(3)
        self.tablaLista.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255, 0))
        self.tablaLista.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255, 0))
        self.tablaLista.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255, 0))
        self.tablaLista.setHorizontalHeaderItem(2, item)

        self.retranslateUi(Dialog)
        self.btnsalir.accepted.connect(Dialog.accept) # type: ignore
        self.btnsalir.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.actualizarTabla()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Listar Videojuegos"))
        item = self.tablaLista.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Codigo"))
        item = self.tablaLista.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nombre"))
        item = self.tablaLista.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Num de horas"))
    
    def actualizarTabla(self):
        numfilas = len(videojuegos.Lista)
        numColumnas = len(videojuegos.Lista[0])
        self.tablaLista.setColumnCount(numColumnas)
        self.tablaLista.setRowCount(numfilas)
        for fila in range(numfilas):
            for columma in range(numColumnas):
                item = videojuegos.Lista[fila][columma]
                print(item)
                self.tablaLista.setItem(fila-1, columma, QtWidgets.QTableWidgetItem(item))
