# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled/form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import QAdd
import QLista
import QDelete
import Videojuegos


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        MainWindow.setMinimumSize(QtCore.QSize(400, 300))
        MainWindow.setMaximumSize(QtCore.QSize(400, 300))
        MainWindow.setBaseSize(QtCore.QSize(400, 300))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(400, 300))
        self.centralwidget.setMaximumSize(QtCore.QSize(400, 300))
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setBaseSize(QtCore.QSize(400, 300))
        self.centralwidget.setObjectName("centralwidget")
        self.btnListar = QtWidgets.QPushButton(self.centralwidget)
        self.btnListar.setGeometry(QtCore.QRect(130, 50, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnListar.setFont(font)
        self.btnListar.setObjectName("btnListar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 10, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnAniadir = QtWidgets.QPushButton(self.centralwidget)
        self.btnAniadir.setGeometry(QtCore.QRect(130, 90, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnAniadir.setFont(font)
        self.btnAniadir.setObjectName("btnAniadir")
        self.btnModificar = QtWidgets.QPushButton(self.centralwidget)
        self.btnModificar.setGeometry(QtCore.QRect(130, 170, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnModificar.setFont(font)
        self.btnModificar.setObjectName("btnModificar")
        self.btnEliminar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEliminar.setGeometry(QtCore.QRect(130, 130, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setObjectName("btnEliminar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 270, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnListar.clicked.connect(self.openLista)
        self.btnAniadir.clicked.connect(self.openAniadir)
        self.btnEliminar.clicked.connect(self.openEliminar)
        self.btnModificar.clicked.connect(self.openModificar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ejercicio Serializable"))
        self.btnListar.setText(_translate("MainWindow", "Listar"))
        self.label.setText(_translate("MainWindow", "Lista de videojuegos"))
        self.btnAniadir.setText(_translate("MainWindow", "Añadir"))
        self.btnModificar.setText(_translate("MainWindow", "Modificar"))
        self.btnEliminar.setText(_translate("MainWindow", "Eliminar"))
        self.label_3.setText(_translate("MainWindow", "Hecho por: Pablo García Manzano"))

    def openLista(self):
        videojuegos = Videojuegos.Videojuegos()
        dialog = QtWidgets.QDialog()
        if len(videojuegos.Lista) == 0 or len(videojuegos.Lista[0]) == 0:
            QtWidgets.QMessageBox.question(dialog, 'Error', 'La lista de videojuegos esta vacia',
                    QtWidgets.QMessageBox.Yes)
        else:
            qLista = QLista.Ui_Dialog()
            qLista.setupUi(dialog)
            dialog.exec_()
    def openAniadir(self):
        videojuegos = Videojuegos.Videojuegos()
        dialog = QtWidgets.QDialog()
        qAniadir = QAdd.Ui_Dialog()
        qAniadir.setupUi(dialog)
        dialog.exec_()

    def openEliminar(self):
        videojuegos = Videojuegos.Videojuegos()
        dialog = QtWidgets.QDialog()
        if len(videojuegos.Lista) == 0:
            QtWidgets.QMessageBox.question(dialog, 'Error', 'La lista de videojuegos esta vacia',
                    QtWidgets.QMessageBox.Yes)    
        else:
            qEliminar = QDelete.Ui_Dialog()
            qEliminar.setupUi(dialog)
            dialog.exec_()
    
    def openModificar(self):
        videojuegos = Videojuegos.Videojuegos()
        dialog = QtWidgets.QDialog()
        if len(videojuegos.Lista) == 0:
            QtWidgets.QMessageBox.question(dialog, 'Error', 'La lista de videojuegos esta vacia',
                    QtWidgets.QMessageBox.Yes)    
        else:
            
            dialog.exec_()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
